export class UserModel {
    userId: number;
    userTypeId: number;
    rcAgencyId: number;
    userName: string;
    firstName: string;
    middleName?: any;
    lastName: string;
    fullName: string;
    password?: any;
    conformPassword;
    txnPassword?: any;
    passwordSalt?: any;
    address?: any;
    contactNo?: any;
    mobileNo?: any;
    mobilePin?: any;
    email: string;
    memberId;
    bankId;
    warehouseId;
    passwordQuestion?: any;
    passwordAnswer?: any;
    passwordExpire?: any;
    isComplexPassword: boolean;
    isPasswordNeverExpire: boolean;
    isFirstLogin: boolean;
    isPasswordJustReset: boolean;
    isApproved: boolean;
    isLockedOut: boolean;
    isSendNewsOffer: boolean;
    lastLoginDate?: any;
    lastPasswordChangedDate?: any;
    lastLockoutdate?: any;
    failedPasswordAttemptCount?: any;
    failedPasswordAttemptWindowStart?: any;
    failedPasswordAnswerAttemptCount?: any;
    failedPasswordAnswerAttemptWindowStart?: any;
    comment?: any;
    visitorIp?: any;
    tokenTypeId?: any;
    token?: any;
    confirmationCode?: any;
    confirmationCodeType?: any;
    confirmationBy?: any;
    confirmationCodeRequestDate?: any;
    confirmationCodeExpiryDateTime?: any;
    userInRole?: any;
    isActive: boolean;
    status: number;
    createdBy?: any;
    createdOn: string;
    modifiedBy?: any;
    modifiedOn?: any;
    verifiedBy?: any;
    verifiedOn?: any;
}
